export const menuData = {
  entreesChaudes: [
    { id: 101, name: "Falafel", description: "Beignets de fèves et pois chiches, épices douces", price: "7,50 €" },
    { id: 102, name: "Kébé", description: "Beignets de blé concassé et viande de bœuf", price: "7,50 €" },
    { id: 103, name: "Sfihat", description: "Petites pizzas à la viande hachée, tomates et oignons", price: "7,50 €" },
    { id: 104, name: "Fatayere", description: "Chaussons aux épinards et pignons de pin, huile d’olive", price: "7,50 €" },
    { id: 105, name: "Samboussek", description: "Chaussons au fromage ou au poulet", price: "5,50 €" },
    { id: 106, name: "Arayesse", description: "Pain grillé farci de viande hachée, persil et oignons", price: "8,00 €" },
    { id: 107, name: "Jawaneh", description: "Ailes de poulet grillées marinées à l’ail et au citron", price: "7,50 €" },
    { id: 108, name: "Sawda", description: "Foies de volaille marinés à l’ail et au citron", price: "7,50 €" },
  ],
  entreesFroides: [
    { id: 201, name: "Hommos", description: "Purée de pois chiches, ail, citron, huile de sésame", price: "7,00 €" },
    { id: 202, name: "Moutabal", description: "Caviar d’aubergines, citron, huile de sésame", price: "7,00 €" },
    { id: 203, name: "Taboulé", description: "Persil, tomates, blé concassé, citron, huile d’olive", price: "7,00 €" },
    { id: 204, name: "Fattouche", description: "Salade orientale au pain grillé", price: "7,50 €" },
    { id: 205, name: "Warak Inab", description: "Feuilles de vigne farcies au riz, persil et tomates", price: "7,00 €" },
    { id: 206, name: "Moussaka", description: "Aubergines, pois chiches, oignons, sauce tomate", price: "7,00 €" },
    { id: 207, name: "Labneh", description: "Fromage blanc, menthe, huile d’olive", price: "5,00 €" },
    { id: 208, name: "Samkeh Harra", description: "Thon, sauce piquante, oignons, ail et coriandre", price: "7,00 €" },
  ],
  mezzes: [
    { id: 301, name: "Mezzé", description: "12 entrées chaudes et froides", price: "22,00 €" },
    { id: 302, name: "Mezzé complet", description: "10 entrées + plateau de grillades mixtes (chiche kebab, chiche taouk, kafta)", price: "28,00 €" },
    { id: 303, name: "½ Mezzé + grillades mixtes", description: "6 entrées chaudes et froides + plateau de grillades", price: "25,00 €" },
    { id: 304, name: "Mezzé végétarien", description: "Hommos, taboulé, moutabal, falafel, samboussek", price: "17,00 €" },
  ],
  grillades: [
    { id: 401, name: "Chiche Kebab", description: "Brochette d’agneau et légumes grillés", price: "18,00 €" },
    { id: 402, name: "Chiche Taouk", description: "Brochette de poulet mariné aux épices douces et citron", price: "17,00 €" },
    { id: 403, name: "Kafta", description: "Brochette de viande hachée, persil et oignons", price: "17,00 €" },
    { id: 404, name: "Chawarma", description: "Viande de bœuf marinée aux épices douces", price: "17,00 €" },
    { id: 405, name: "Mixte", description: "Assortiment de kebab, taouk et kafta", price: "18,00 €" },
    { id: 406, name: "Le Cèdre", description: "Chawarma, kafta, taouk, taboulé, hommos, moutabal", price: "18,00 €" },
  ],
  desserts: [
    { id: 501, name: "Baklawa", description: "Pâte feuilletée aux amandes", price: "3,50 €" },
    { id: 502, name: "Barma", description: "Pistaches ou amandes enrobées de cheveux d’ange grillés", price: "3,50 €" },
    { id: 503, name: "Maamoul", description: "Gâteaux fourrés aux noix, pistaches ou dattes", price: "3,50 €" },
    { id: 505, name: "Mouhallabieh", description: "Flan libanais à la fleur d’oranger et pistaches", price: "3,00 €" },
    { id: 506, name: "Glace", description: "à la boule", price: "2,00 €" },
  ],
  aperitifs: [
    { id: 601, name: "Arak", description: "Boisson anisée", price: "4,50 €" },
    { id: 602, name: "Kir", description: "", price: "4,50 €" },
    { id: 603, name: "Whisky", description: "", price: "5,00 €" },
    { id: 604, name: "Martini", description: "Rouge, blanc ou rosé", price: "5,00 €" },
    { id: 605, name: "Cocktail de fruits maison", description: "", price: "6,50 €" },
    { id: 606, name: "Cocktail de fruits avec alcool", description: "", price: "6,00 €" },
  ],
  boissons: [
    { id: 701, name: "Sodas / Jus / Ice Tea", description: "Coca-Cola, Jus de fruits...", price: "3,00 €" },
    { id: 702, name: "Eaux (50 cl)", description: "Vittel, Perrier, San Pellegrino", price: "3,00 €" },
    { id: 703, name: "Eaux (1 L)", description: "Vittel, Pellegrino, Badoit", price: "5,00 €" },
    { id: 704, name: "Bières", description: "1664 / Heineken / Almaza (Libanaise)", price: "4,50 €" },
    { id: 705, name: "Café ou Thé à la menthe", description: "", price: "2,00 €" },
  ],
  vins: [
    { id: 801, name: "Vins Libanais (37 cl)", description: "Ksara, Héritage, Kefraya", price: "16,00 €" },
    { id: 802, name: "Vins Libanais (75 cl)", description: "Ksara, Héritage, Kefraya", price: "25,00 €" },
    { id: 803, name: "Vins Marocains", description: "Boulaouane (37cl: 13€ | 75cl: 17€)", price: "dès 13 €" },
    { id: 804, name: "Vins Français (St-Chinian, Faugères)", description: "37cl: 11€ | 75cl: 15€", price: "dès 11 €" },
    { id: 805, name: "Vins en carafe", description: "Pichet 50cl: 11€ | 25cl: 6€ | Verre: 3,50€", price: "dès 3,50 €" },
  ]
};
